Modulo acceso cp 91
eGuerrero-DGTIC/caja-prevsocial pull request #10
Opened 2023-02-01 20:20 UTC by javaprogramer1985

## Descripción de cambios

- Se crean archivos para crear la pantalla que indica que la cuenta esta bloqueada
- Se genera el widget a partir de los archivos

## Enlaces relacionados
- Ticket de Jira: CP-91 MA | Crear la interfaz para mostrar un mensaje cuando la cuenta del usuario esté bloqueada y no permitirle más intentos para iniciar sesión

## Pruebas realizadas

- [X ] Prueba Manual
- [ ] Pruebas E2E (Cypress)
- [ ] Unit testing

### Fotos de antes y después
![image](https://user-images.githubusercontent.com/31780387/216153150-eae344a0-d5d3-41ec-ac02-ef075f484cf3.png)

### Video

2023-02-01 21:31 UTC, luisabarca commented on nextjs/src/components/cuerpo_mensaje/index.tsx
> +    fontCuerpo: {
Sería mejor usar `fontVariant`

2023-02-01 21:46 UTC, luisabarca requested changes

2023-02-01 21:46 UTC, luisabarca commented on nextjs/src/components/frame/frame-base.stories.tsx
> +/*export default {
Eliminar código no ejecutable o comentado

2023-02-01 21:46 UTC, luisabarca commented on nextjs/src/components/frame/frame-base.stories.tsx
> +    frameType?: "Begin"|"Notifications";
```suggestion
    frameType?: "begin" | "notifications";
```

2023-02-01 21:46 UTC, luisabarca commented on nextjs/src/components/frameMensaje/index.tsx
> +    bg: {
```suggestion
    bgColor: {
```

2023-02-01 21:46 UTC, luisabarca commented on nextjs/src/components/widgets/account-Inactive.tsx
> +    position: {
Opcionalmente este variant se puede cambiar a `centered` o `centrado` para usarlo como:

```
// Normal
<Wrapper />

// Centrado
<Wrapper centered />
```

2023-02-01 21:46 UTC, luisabarca commented on nextjs/src/components/widgets/account-Inactive.tsx
> +  margin: "0rem auto",
```suggestion
  margin: "0 auto",
```

2023-02-01 21:46 UTC, luisabarca commented on nextjs/src/components/widgets/mensaje-estatus.tsx
> +  cuerpo_p1,
Apegarse a camelCase para los props

```suggestion
  cuerpoParrafoArriba,
```

2023-02-01 21:46 UTC, luisabarca commented on nextjs/src/components/widgets/mensaje-estatus.tsx
> +  titulo2,
```suggestion
  subtitulo,
```

2023-02-02 16:34 UTC, rodgutna reviewed
pruebs de revisar todo de golpe, sin colocar el revisado en cada archivo

2023-02-08 16:12 UTC, javaprogramer1985 commented on nextjs/src/components/cuerpo_mensaje/index.tsx
> +    fontCuerpo: {
Se elimino este archivo por que se uso Labels

2023-02-08 16:12 UTC, javaprogramer1985 commented on nextjs/src/components/frameMensaje/index.tsx
> +    bg: {
Se hizo el cambio.

2023-02-08 18:31 UTC, luisabarca submitted a review, later dismissed
👍

2023-02-10 21:03 UTC, rodgutna reviewed
Excelente trabajo

2023-02-10 21:03 UTC, rodgutna approved these changes
ahora si ya

2023-02-10 21:10 UTC, merged