Labels
eGuerrero-DGTIC/caja-prevsocial pull request #9
Opened 2023-02-01 18:10 UTC by ddbosston

## Descripción de cambios

* Se creó widget, que contiene la pantalla cuenta desactivada.
* Se agrega primera versión del componente label: permite crear etiquetas con el tipo de letra "LTinternet", además acepta cualquier objeto o componete como hijo dentro de la misma.
* Se agrega segunda versión del componente frame: permite crear un contenedor de componentes abarcar todo la pantalla o una ventana de notificación.

## Enlaces relacionados
- Ticket de Jira: MA_07_Cuenta desactivada

## Pruebas realizadas

- [X ] Prueba Manual
- [ ] Pruebas E2E (Cypress)
- [ ] Unit testing

### Fotos de antes y después
Ejemplo de pantalla que corresponde a la cuenta inactiva
![image](https://user-images.githubusercontent.com/7682302/216126228-65372b9c-05bf-4f68-8298-5bfb40cf074c.png)

### Video

2023-02-01 21:26 UTC, luisabarca requested changes

2023-02-02 15:51 UTC, rodgutna commented on nextjs/src/components/frame/frame-base.stories.tsx
> +/*export default {
de acuerdo, debemos eliminar comentarios incecesarios

2023-02-02 15:53 UTC, rodgutna commented on nextjs/src/components/frame/frame-base.tsx
> +    color:{
en mi caso debo repasar css 😿

2023-02-02 15:54 UTC, rodgutna commented on nextjs/src/components/label/label-base.tsx
> +  fontFamily: "fonts/LTInternet-Regular.ttf",
entendido, asi se hace mas general el uso de dichos binarios para todos los componentes

2023-02-02 15:55 UTC, rodgutna commented on nextjs/src/components/widgets/account-Inactive.tsx
> +  margin: "0rem auto",
mismo comentario, al menos de mi parte desempolvar css

2023-02-02 15:56 UTC, rodgutna commented on nextjs/src/pages/tablero/inactiva/index.page.tsx
> +const CuentaIna = () => {
no usar codigo ninja de los programadores de la vieja escuela.
https://javascript.info/ninja-code

2023-02-02 15:58 UTC, rodgutna reviewed
se puede aplicar la sugerencia para mejorar los detalles de codigo

2023-02-03 15:43 UTC, ddbosston commented on nextjs/src/components/frame/frame-base.stories.tsx
> +/*export default {
Ok de acuerdo

2023-02-03 15:44 UTC, ddbosston commented on nextjs/src/components/frame/frame-base.tsx
> +    frameType?: "Begin"|"Notifications",
Ok cambiará a minúsculas

2023-02-03 15:46 UTC, ddbosston commented on nextjs/src/components/label/label-base.tsx
> +  fontFamily: "fonts/LTInternet-Regular.ttf",
Por el momento parece ser del componente

2023-02-03 15:47 UTC, ddbosston commented on nextjs/src/pages/tablero/inactiva/account-ina.tsx
> +    return <div>Estás intentando acceder a contenido protegido xxxxxxxxxxxxxxxxxxxxx</div>;
Ok se quita link n0p07

2023-02-04 02:44 UTC, luisabarca commented on nextjs/src/components/frame/frame-base.stories.tsx
> +export type FrameProps = React.PropsWithChildren & {
Se puede eliminar todo esto si se importan los props del componente

```suggestion

```

Cambiar 
`import { Frame } from "./frame-base";`

 Por:
```
import type { FrameProps } from "./frame-base";
import { Frame } from "./frame-base";
```

2023-02-04 02:45 UTC, luisabarca commented on nextjs/src/components/label/label-base.stories.tsx
> +export type TextProps = React.PropsWithChildren & {
Lo mismo con los props aquí, no debemos crear/exportar nuevos types, la idea es probar los del componente

2023-02-04 02:46 UTC, luisabarca approved these changes

2023-02-08 17:42 UTC, ddbosston commented on nextjs/src/components/label/label-base.stories.tsx
> +export type TextProps = React.PropsWithChildren & {
Ok quitaron los exports

2023-02-08 17:43 UTC, ddbosston commented on nextjs/src/components/frame/frame-base.stories.tsx
> +export type FrameProps = React.PropsWithChildren & {
De acuerdo se actualizó código con la sugerencia que mencionas.

2023-02-10 17:31 UTC, merged